### ISSUE TITLE
Python packaging on a branch

### ISSUE THREAD

**Issue by grzanka** [libamtrack/library#196]
```
 create mode 100644 include/AT_Histograms.h
 create mode 100644 include/AT_KatzModel.h
 create mode 100644 include/AT_KatzModel_Implementation.h
 create mode 100644 include/AT_MultipleCoulombScattering.h
 create mode 100644 include/AT_NumericalRoutines.h
 create mode 100644 include/AT_PhysicsRoutines.h
 create mode 100644 include/AT_ProbabilityDistributions.h
 create mode 100644 include/AT_ProtonAnalyticalBeamParameters.h
 create mode 100644 include/AT_ProtonAnalyticalModels.h
 create mode 100644 include/AT_RDD.h
 create mode 100644 include/AT_RDD_ExtendedTarget.h
 create mode 100644 include/AT_RDD_ShellAveraged.h
 create mode 100644 include/AT_RDD_Simple.h
 create mode 100644 include/AT_RDD_Tabulated.h
 create mode 100644 include/AT_SPC.h
 create mode 100644 include/AT_StoppingPower.h
 create mode 100644 include/AT_StoppingPowerData.h
 create mode 100644 include/AT_StoppingPowerDataBethe.h
 create mode 100644 include/AT_StoppingPowerDataFromFile.h
 create mode 100644 include/AT_StoppingPowerDataICRU.h
 create mode 100644 include/AT_StoppingPowerDataPSTAR.h
 create mode 100644 include/AT_SuccessiveConvolutions.h
 create mode 100644 src/AT.c
 create mode 100644 src/AT_Algorithms_CPP.c
 create mode 100644 src/AT_Algorithms_GSM.c
 create mode 100644 src/AT_Algorithms_IGK.c
 create mode 100644 src/AT_Constants.c
 create mode 100644 src/AT_DataMaterial.c
 create mode 100644 src/AT_DataParticle.c
 create mode 100644 src/AT_DataRange.c
 create mode 100644 src/AT_ElectronRange.c
 create mode 100644 src/AT_EnergyLoss.c
 create mode 100644 src/AT_Error.c
 create mode 100644 src/AT_GammaResponse.c
 create mode 100644 src/AT_Histograms.c
 create mode 100644 src/AT_KatzModel.c
 create mode 100644 src/AT_KatzModel_Implementation.c
 create mode 100644 src/AT_MultipleCoulombScattering.c
 create mode 100644 src/AT_NumericalRoutines.c
 create mode 100644 src/AT_PhysicsRoutines.c
 create mode 100644 src/AT_ProbabilityDistributions.c
 create mode 100644 src/AT_ProtonAnalyticalBeamParameters.c
 create mode 100644 src/AT_ProtonAnalyticalModels.c
 create mode 100644 src/AT_RDD.c
 create mode 100644 src/AT_RDD_ExtendedTarget.c
 create mode 100644 src/AT_RDD_ShellAveraged.c
 create mode 100644 src/AT_RDD_Simple.c
 create mode 100644 src/AT_RDD_Tabulated.c
 create mode 100644 src/AT_SPC.c
 create mode 100644 src/AT_StoppingPower.c
 create mode 100644 src/AT_StoppingPowerData.c
 create mode 100644 src/AT_StoppingPowerDataBethe.c
 create mode 100644 src/AT_StoppingPowerDataFromFile.c
 create mode 100644 src/AT_StoppingPowerDataICRU.c
 create mode 100644 src/AT_StoppingPowerDataPSTAR.c
 create mode 100644 src/AT_SuccessiveConvolutions.c
 create mode 100644 src/index.dox
/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/integration.py:39: RuntimeWarning: 
ERROR: setuptools==41.6.0 is used in combination with setuptools_scm>=6.x

Your build configuration is incomplete and previously worked by accident!


This happens as setuptools is unable to replace itself when a activated build dependency
requires a more recent setuptools version
(it does not respect "setuptools>X" in setup_requires).


setuptools>=31 is required for setup.cfg metadata support
setuptools>=42 is required for pyproject.toml configuration support

Suggested workarounds if applicable:
 - preinstalling build dependencies like setuptools_scm before running setup.py
 - installing setuptools_scm using the system package manager to ensure consistency
 - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools

  """
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    'Programming Language :: Python :: 3.10'
  File "/opt/python/cp36-cp36m/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/opt/python/cp36-cp36m/lib/python3.6/site-packages/setuptools/dist.py", line 447, in __init__
    k: v for k, v in attrs.items()
  File "/opt/python/cp36-cp36m/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/opt/python/cp36-cp36m/lib/python3.6/site-packages/setuptools/dist.py", line 735, in finalize_options
    ep.load()(self, ep.name, value)
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/integration.py", line 75, in version_keyword
    _assign_version(dist, config)
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/integration.py", line 48, in _assign_version
    maybe_version = _get_version(config)
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/__init__.py", line 151, in _get_version
    parsed_version = _do_parse(config)
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/__init__.py", line 98, in _do_parse
    version = _version_from_entrypoints(config) or _version_from_entrypoints(
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/_entrypoints.py", line 37, in _version_from_entrypoints
    version: Optional[ScmVersion] = _call_entrypoint_fn(root, config, ep.load())
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/_entrypoints.py", line 13, in _call_entrypoint_fn
    return fn(root, config=config)
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/git.py", line 147, in parse
    config, wd, describe_command=describe_command, pre_parse=pre_parse
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/git.py", line 188, in _git_parse_inner
    config=config,
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/version.py", line 193, in meta
    parsed_version = _parse_tag(tag, preformatted, config)
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/version.py", line 174, in _parse_tag
    tag = tag_to_version(tag, config)
  File "/io/generated/.eggs/setuptools_scm-6.4.2-py3.6.egg/setuptools_scm/version.py", line 80, in tag_to_version
    version = config.version_cls(version)
  File "/opt/python/cp36-cp36m/lib/python3.6/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'v0.13.0-3-g902ef63'
/io/generate_inside_docker.sh: line 47: cd: /io/generated/dist: No such file or directory
usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot access *whl. No such file
ls: cannot access 'generated/dist/': No such file or directory
```

**Comment by grzanka** [comment]
Seems fixed by PR #197
